<?php
$input = array("Animal Transformation",
"Bodysharing", 
"Bodyswap", 
"Elf AU", 
"Genderswap", 
"Ghosts", 
"Magic AU", 
"Merpeople", 
"Robots", 
"Vampire", 
"Werewolf", 
"Wingfic", 
"Zombies", 
"Alpha/Beta/Omega society", 
"Barista AU", 
"Bakery AU", 
"BDSM AU", 
"Cyberpunk AU", 
"High School AU", 
"University AU", 
"Historical AU", 
"Noir Detective AU", 
"Prison AU", 
"Regency AU", 
"Royalty AU", 
"Pirate AU", 
"Pornstar AU", 
"Hooker AU", 
"Hitman/Assassin AU", 
"Apocalypse", 
"Epistolary", 
"Domesticity", 
"Bed Sharing", 
"Accidental Marriage", 
"Arranged Marriage", 
"Kidfic", 
"Weddingfic", 
"Crossover", 
"Harlequin", 
"Holidayfic", 
"Hurt/Comfort", 
"Reincarnation", 
"Tentacles", 
"Time Travel", 
"Amnesia", 
"Deathfic", 
"Didn't Know They Were Dating", 
"Doppelgangers/Evil Twins", 
"First Time", 
"Huddling for Warmth", 
"Mind control", 
"Pregnancy", 
"Presumed Dead", 
"Fake Dating", 
"Fuck or Die", 
"Sex Pollen", 
"Darkfic", 
"Missing scene/episode tag", 
"Fix-it", 
"Futurefic", 
"Next generation -- canon characters' children", 
"Backstory", 
"Angst", 
"Crack", 
"Emoporn", 
"Fluff", 
"Porn, PWP", 
"Schmoop", 
"Smarm",
"Hogwarts AU",
"Sci-fi",
"Utopia/Dystopia AU",
"Role Reversal",
"Kidnapping",
"Celebratory Kiss",
"Coming Out",
"Blackmail",
"Bets/Wagers",
"Competition",
"Reality Show",
"Music/Band",
"Last Time",
"Handcuffed/Bound Together",
"Immortality",
"Matchmaker",
"Meet the Family",
"Miscommunication",
"Reunion",
"Roadtrip",
"Slavefic",
"Adopting/Raising a Baby",
"Food Service AU",
"Enemies to Friends to Lovers",
"Soulmate Identifying Marks: Tattoo, Red Thread of Fate, etc",
"Seemingly Unrequited Pining",
"Actually Unrequited Pining",
"Fake Out Make Out",
"'Groundhog Day'/Karmic Time Warp",
"Espionage AU",
"Rivalmancy",
"Friends to Lovers",
"Loyalty Kink",
"Selfcest (possibly due to time travel)",
"Age Difference (possibly due to time travel)",
"Werewolves",
"Magical Connection (telepathy, etc)");
$rand_keys = array_rand($input, 2);
echo $input[$rand_keys[0]] . "";

?>